use crate::checks::shell;
use crate::output::HookOutput;

const GENERATED_BY: &str = "The message carries a generated-with attribution line. CLAUDE.md: no \
🤖, no emoji, no generated-by line and no claude.ai/code link in a commit, tag, PR/MR body or \
review comment — `Co-Authored-By` is the only trailer that lands, and the harness supplies it. \
Drop the line and run the command again.";

/// Programs whose write verbs put text in front of humans and keep it there.
/// `glab` is matched by prefix: the group-token wrappers CLAUDE.md posts as the
/// bot with are named after it.
fn writes_for_humans(program: &str) -> Option<&'static [&'static str]> {
    match program {
        "git" => Some(&["commit", "tag"]),
        "gh" => Some(FORGE_VERBS),
        _ if program.starts_with("glab") => Some(FORGE_VERBS),
        _ => None,
    }
}

/// Forge verbs that carry a body. `create` and `update` take `--description`,
/// the rest a comment.
const FORGE_VERBS: &[&str] = &["create", "update", "note", "comment", "edit", "reply"];

/// Denies a commit, tag or forge body carrying an attribution line. The line is
/// what a harness attribution block asks for and what CLAUDE.md forbids, so it
/// arrives already written and nothing in the session's own context objects.
pub fn check(command: &str) -> Option<HookOutput> {
    (writes_a_body(command) && carries_attribution(command))
        .then(|| HookOutput::deny("PreToolUse", GENERATED_BY))
}

/// A write verb belonging to one of the programs above. Read from the whole text
/// rather than through `chain_segments`, which gives up on the heredoc a commit
/// message arrives in: a verb is one word, and a body naming it sits behind a
/// program word that names nothing.
fn writes_a_body(command: &str) -> bool {
    let tokens: Vec<&str> = shell::before_heredoc(command)
        .split_whitespace()
        .collect();
    tokens
        .iter()
        .enumerate()
        .any(|(i, token)| {
            let Some(verbs) = writes_for_humans(basename(shell::unquote_token(token))) else {
                return false;
            };
            tokens[i + 1..]
                .iter()
                .take_while(|word| !word.ends_with([';', '&', '|']))
                .any(|word| verbs.contains(&shell::unquote_token(word)))
        })
}

/// An attribution line, anchored to the start of a line so prose naming one — this
/// deny's own commit message included — is not one. Leading quotes and list
/// markers are stripped: the line arrives inside a quoted argument, sometimes as
/// the first thing in it.
fn carries_attribution(text: &str) -> bool {
    // A body written with `\n` escapes reaches the forge as the same lines, so the
    // escape breaks a line here too.
    text.replace("\\n", "\n")
        .lines()
        .any(|line| {
            let line = line
                .trim_start()
                .trim_start_matches(['"', '\'', '-', '*', '#', ' ']);
            if line.starts_with('🤖') {
                return true;
            }
            let lower = line.to_ascii_lowercase();
            lower.contains("claude")
                && [
                    "generated with",
                    "generated by",
                    "created with",
                    "co-created with",
                ]
                .iter()
                .any(|opening| lower.starts_with(opening))
        })
}

fn basename(word: &str) -> &str {
    word.rsplit('/')
        .next()
        .unwrap_or(word)
}

#[cfg(test)]
mod tests {
    use super::check;

    fn denied(command: &str) -> bool {
        check(command).is_some()
    }

    #[test]
    fn an_attribution_line_in_a_body_is_refused() {
        for cmd in [
            "glab-wrapper mr create --title x --description \"body text\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\"",
            "gh pr create --body \"fix\n\nGenerated with Claude Code\"",
            "glab mr note 2408 -m \"reply\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\"",
            "git add x && git commit -F - <<'EOF'\nfeat: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\nEOF",
            "git tag -F - v1.0 <<'EOF'\nv1.0\n\nCreated with Claude Code\nEOF",
        ] {
            assert!(denied(cmd), "{cmd}");
        }
    }

    #[test]
    fn everything_else_passes() {
        for cmd in [
            // The trailer CLAUDE.md does want.
            "git commit -F - <<'EOF'\nfeat: x\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\nEOF",
            // Prose describing the rule, which this repo's own commits carry.
            "git commit -F - <<'EOF'\nfeat(attribution): deny a 🤖 generated-with line in a body\nEOF",
            // A read, whatever its output holds.
            "glab mr view 2408",
            "git log --grep 'Generated with Claude Code'",
        ] {
            assert!(!denied(cmd), "{cmd}");
        }
    }
}
