//! `rules` — the shapes this binary auto-allows, printed for the caller that
//! would otherwise write the one that prompts. A caller cannot infer an allow
//! from a refusal it never sees, and a shape it cannot predict it does not use.
//!
//! Written for a model reading it out of `CLAUDE.md`: shapes, no reasons. Widen
//! it with the check that widens the allow.

use std::path::{Path, PathBuf};

/// Regenerated by `make release`, so the file a `CLAUDE.md` imports cannot lag the
/// binary deciding the allows.
pub const FILE: &str = "docs/allowed-commands.md";

pub const RULES: &str = r#"# Commands allowed without a permission prompt

Generated by `ticpu-claude-command-hook rules` — do not edit this file.

Anything not listed here keeps its normal prompt. A `$(…)` or a backtick anywhere in the
command forfeits every allow below, as does any redirect (`>`, `2>file`) and any consumer
that can run or write something (`| sh`, `| xargs rm`, `| tee`).

## Journals and units

- `journalctl` with flags that only select what is printed, and `systemctl status`, `show`,
  `cat`, `is-active`, `is-enabled`, `is-failed`, `list-units`, `list-unit-files`,
  `list-timers`, `list-sockets`.
- The same over ssh: `ssh <host> journalctl -u foo -n 200`. Put a pipe *inside* the quotes —
  `ssh <host> 'journalctl -u foo | grep -i error'` is allowed, a `&&` or `;` in there is not.
- ssh options: `-4 -6 -q -T -t -n -C -v`, `-p`, `-l`, `-i`, and `-o` naming `BatchMode`,
  `ConnectTimeout`, `ConnectionAttempts`, `StrictHostKeyChecking`, `LogLevel`,
  `ServerAlive{Interval,CountMax}`, `RequestTTY`, `Port`, `User`.
- Never allowed: `sudo` at either end, `-f`/`--follow`, and anything that writes the journal
  (`--rotate`, `--vacuum-*`, `--flush`, `--sync`).

## git

- Read-only verbs — `status`, `log`, `show`, `diff`, `blame`, `rev-parse`, `grep`,
  `ls-files`, `for-each-ref`, `rev-list`, `check-ignore`, `diff-tree`, … — including under
  `-C <path>`, and the read-only modes of `branch`, `tag`, `config`, `remote`, `reflog`,
  `symbolic-ref`.
- `git add <path>` naming at least one path that exists as a file. `-A`, `.`, `-u` and `*`
  are refused; so is a pathspec spelled from the repo root while you are below it.
- `cd <path> && git …` where the path is in the repo you are already in is refused for any
  other verb: run it from here, or `cd` on its own first — the directory persists between
  calls. A `cd` to a different repo keeps its prompt.

## glab

- Reading verb pairs: `mr view|list|diff|checks`, `issue view|list`, `ci view|list|status|
  trace|get`, `pipeline view|list|status`, `release view|list`, `repo view|list|contributors`,
  `snippet view|list`, `label list`, `milestone list`, `incident view|list`, `schedule list`,
  `auth status`, plus `glab version`.
- `glab api <path>` with no `-X`/`--method` other than GET and no body flag.
- The first `glab` of a session is refused whatever it does; the refusal carries the guidance.

## cargo

- `build`, `check`, `clippy`, `test`, `bench`, `doc`, `rustdoc`, `fmt`, `tree`, `metadata`,
  `info`, `search`, `expand`, `llvm-cov`, `semver-checks` — piped into display-only stages,
  `2>&1` included. `run`, `add`, `update` and `clean` are not on the list.

## Searches

- `grep`/`rg` is rewritten to fold through `gf` and allowed, as long as every other segment
  of the command is one of the shapes above. `2>/dev/null` on a search is refused — use `-s`.

## Anywhere in the chain

- A bare `cd <path>`, an `echo`, a bare `NAME=value` assignment, and a utility that only reads
  and prints — `ls`, `stat`, `wc`, `head`, `tail`, `cat`, `nl`, `file`, `basename`, `dirname`,
  `realpath`, `readlink`, `date`, `uname`, `id`, `printf` — may sit beside any of the above
  without costing the allow. Any other command in the chain forfeits it, and a segment carrying
  a `$(…)` forfeits it whatever it is.
- A `cat` that opens a file is refused ahead of all of it — use the Read tool, or a flag
  (`-A`, `-n`, `-v`, `-T`, `-E`) — so it rides along only where it reads a pipe. Refused too:
  one file piped into another program, which can open it itself. Several files joined is not.
  The refusal names a waiver, and `touch "$XDG_RUNTIME_DIR/claude-hooks/cat-read-waiver"`
  alone on the command line is allowed without a prompt; every other marker's creation is
  prompted.
- The assignment only counts while nothing expands it: `P=/some/path; cmd $P` is *refused*.
  Write the value where it is used — the allows above match the command text, and the
  assignment in front of it makes the call match none of them. A computed value (`P=$(…)`)
  is not this and keeps its normal prompt.
"#;

pub fn print() {
    print!("{RULES}");
}

/// The generated file's path, from this binary's own `target/<profile>/` location,
/// so `install` can name the line to import. `None` when the binary was moved out
/// of its checkout, where there is nothing to point a `CLAUDE.md` at.
pub fn doc_path(binary: &Path) -> Option<PathBuf> {
    let root = binary
        .ancestors()
        .nth(3)?;
    let path = root.join(FILE);
    path.is_file()
        .then_some(path)
}
