//! `rules` — the shapes this binary auto-allows, printed for the caller that
//! would otherwise write the one that prompts. A caller cannot infer an allow
//! from a refusal it never sees, and a shape it cannot predict it does not use.
//!
//! Written for a model reading it out of `CLAUDE.md`: shapes, no reasons. Widen
//! it with the check that widens the allow.
//!
//! It is imported into every session, so it is priced per token: one flat line
//! per shape, no headings, no bullets, no blank lines, no emphasis, and no
//! sentence that explains rather than states. Articles and connectives go too —
//! what has to survive verbatim is every command word, flag and path.

use std::path::{Path, PathBuf};

/// Regenerated by `make release`, so the file a `CLAUDE.md` imports cannot lag the
/// binary deciding the allows.
pub const FILE: &str = "docs/allowed-commands.md";

pub const RULES: &str = r#"Auto-allowed shapes, generated by ticpu-claude-command-hook rules. Do not edit.
Not listed: normal prompt. Every allow forfeited by $(…) or a backtick anywhere, any redirect (>, 2>file), any consumer that runs or writes (| sh, | xargs rm, | tee).
journalctl with print-selecting flags. systemctl status show cat is-active is-enabled is-failed list-units list-unit-files list-timers list-sockets.
Both over ssh: ssh <host> journalctl -u foo -n 200. Pipe inside the quotes yes, && or ; inside no.
ssh options: -4 -6 -q -T -t -n -C -v -p -l -i, -o BatchMode ConnectTimeout ConnectionAttempts StrictHostKeyChecking LogLevel ServerAliveInterval ServerAliveCountMax RequestTTY Port User.
Never: sudo either end, -f/--follow, journal writes (--rotate --vacuum-* --flush --sync).
git read verbs: status log show diff blame rev-parse grep ls-files for-each-ref rev-list check-ignore diff-tree …, under -C <path> too; read-only modes of branch tag config remote reflog symbolic-ref.
git add <path> naming at least one path existing as a file. Refused: -A . -u *, pathspec spelled from repo root while below it.
git commit -F - <<'EOF' … EOF, delimiter quoted, terminator last line. Flags: -F - --file=- -s --signoff -q --quiet. Refused: -a --amend -m, a pathspec, -C, -c, an unquoted <<EOF.
cd <path> && git … inside the current repo: refused for every other verb; run from here, or bare cd first (directory persists between calls). cd to another repo keeps its prompt.
glab read pairs: mr view|list|diff|checks, issue view|list, ci view|list|status|trace|get, pipeline view|list|status, release view|list, repo view|list|contributors, snippet view|list, label list, milestone list, incident view|list, schedule list, auth status, glab version.
glab api <path>: GET only, no body flag.
First glab of a session: refused whatever it does, refusal carrying the guidance.
cargo build check clippy test bench doc rustdoc fmt tree metadata info search expand llvm-cov semver-checks, piped into display-only stages, 2>&1 included. Not run, add, update, clean.
grep/rg rewritten to fold through gf and allowed while every other segment is a shape above. 2>/dev/null on a search refused, use -s.
Rides along free: bare cd <path>, echo, bare NAME=value, read-and-print utility (ls stat wc head tail cat nl file basename dirname realpath readlink date uname id printf). Any other command forfeits the allow, so does $(…) in any segment.
NAME=value counts only while nothing expands it: P=/some/path; cmd $P refused, write the value where it is used. P=$(…) keeps its normal prompt.
Waivers live in $XDG_RUNTIME_DIR/claude-hooks/. waiver:<name> means touch "$XDG_RUNTIME_DIR/claude-hooks/<name>", the command each refusal prints, spent by the next refusal it answers. Creating one is prompted, except waiver:cat-read-waiver alone on the line, which is allowed.
cat opening a file: refused ahead of all of it. Read tool, or a flag (-A -n -v -T -E); rides along only reading a pipe. One file piped into another program refused too, several files joined not. Overruled by waiver:cat-read-waiver.
"#;

pub fn print() {
    print!("{RULES}");
}

const PACKAGED_DOC: &str = "share/doc/ticpu-claude-command-hook/allowed-commands.md";

/// The generated file's path, so `install` can name the line to import. `None` when
/// the binary was moved away from both copies, where there is nothing to point a
/// `CLAUDE.md` at.
pub fn doc_path(binary: &Path) -> Option<PathBuf> {
    doc_candidates(binary)
        .into_iter()
        .find(|p| p.is_file())
}

/// A checkout has it three levels up from `target/<profile>/`; the .deb ships it
/// under the prefix the binary sits in.
fn doc_candidates(binary: &Path) -> Vec<PathBuf> {
    let mut candidates = Vec::new();
    if let Some(root) = binary
        .ancestors()
        .nth(3)
    {
        candidates.push(root.join(FILE));
    }
    if let Some(prefix) = binary
        .ancestors()
        .nth(2)
    {
        candidates.push(prefix.join(PACKAGED_DOC));
    }
    candidates
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checkout_and_packaged_locations_are_both_offered() {
        let candidates = doc_candidates(Path::new("/usr/bin/ticpu-claude-command-hook"));
        assert!(candidates.contains(&PathBuf::from(
            "/usr/share/doc/ticpu-claude-command-hook/allowed-commands.md"
        )));

        let candidates = doc_candidates(Path::new(
            "/home/x/repo/target/release/ticpu-claude-command-hook",
        ));
        assert_eq!(
            candidates[0],
            PathBuf::from("/home/x/repo/docs/allowed-commands.md")
        );
    }
}
